site_name: Saplings Documentation
site_description: This recipe is designed to help start a highly configured Drupal project.
site_url: https://kanopi.github.io/saplings
repo_url: https://github.com/kanopi/saplings
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Site Architecture:
    - Content types:
      - Page: content-types-page.md
      - Post: content-types-post.md
      - Event: content-types-event.md
    - Components: components.md
    - Media: media.md
    - Menus: menus.md
    - Taxonomies: taxonomies.md
    - Add ons:
      - Language Switcher: add-on-language-switcher.md
      - Mega Menu: add-on-mega-menu.md
      - Search: add-on-search.md
    - Dependencies: dependencies.md
  - For Designers:
    - Designer Documentation: designers.md
  - For Developers:
    - Developer Documentation: developers.md
  - Recipe Architecture:
    - Introduction: recipes-introduction.md

theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  palette:
    scheme: saplings
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/KanopiStudios
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/kanopi_studios
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/kanopistudios
    - icon: fontawesome/brands/github
      link: https://github.com/kanopi
  generator: false

copyright: Copyright &copy; 2024 - 2025 Kanopi Studios
