name: 'Saplings'
description: 'Modern Drupal starter recipe.'
type: 'Site'
recipes:
  - gin-admin-experience
  - saplings-base
  - saplings-content-types
  - saplings-editorial
  - saplings-launch
  - saplings-theme
  - saplings-tests
